### ISSUE TITLE
Keyboard and trackpad not working

### ISSUE THREAD

**Issue by eeeeeeelukeeeeeeee** [hanngoc1406/ACER-A315-53G-Hackintosh-Opencore#3]
Is there something I'm missing? I've looked through the plist you supplied aswell as the kexts and everything looks good but it just won't pick up the keyboard and trackpad? First time doing opencore so it's probably something stupid I'm missing, any help would be greatly appreciated!

**Comment by oleggtro** [comment]
Same here

**Comment by hanngoc1406** [comment]
i update file to get all work now
