### ISSUE TITLE
No backlight 

### ISSUE THREAD

**Issue by asrorbek-mannonov** [hanngoc1406/ACER-A315-53G-Hackintosh-Opencore#5]
Successfully boot into Catalina 10.15.3 installing window with usb, but no backlight.

**Comment by hanngoc1406** [comment]
You need to delete [SSDT-DiscreteSpoof.aml](https://github.com/hanngoc1406/ACER-A315-53G-Hackintosh-Opencore/blob/master/OC/ACPI/SSDT-DiscreteSpoof.aml) and replace with SSDT-dGPU-Off.aml by flowing this [guide](https://dortania.github.io/Getting-Started-With-ACPI/Laptops/laptop-disable.html). Btw i will update this file later
